name: CI

on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: install elm
        run: npm install elm elm-test elm-format

      - name: elm-format
        run: npx elm-format --validate src/ tests/

      - name: elm-test
        run: npx elm-test
